from .checkpoint_config_node import NODE_CLASS_MAPPINGS as MAP_CHECKPOINT, NODE_DISPLAY_NAME_MAPPINGS as MAP_CHECKPOINT_DISP
from .prompt_builder_node import NODE_CLASS_MAPPINGS as MAP_PROMPT, NODE_DISPLAY_NAME_MAPPINGS as MAP_PROMPT_DISP
from .lora_config_node import NODE_CLASS_MAPPINGS as MAP_LORA, NODE_DISPLAY_NAME_MAPPINGS as MAP_LORA_DISP

NODE_CLASS_MAPPINGS = {**MAP_CHECKPOINT, **MAP_PROMPT, **MAP_LORA}
NODE_DISPLAY_NAME_MAPPINGS = {**MAP_CHECKPOINT_DISP, **MAP_PROMPT_DISP, **MAP_LORA_DISP}

# Comunica a ComfyUI di servire la cartella web locale
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]